# Generated by Django 3.1.7 on 2021-04-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210402_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('drinks', 'drinks'), ('appetizers', 'appetizers'), ('treats', 'treats'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
