# Generated by Django 3.2 on 2021-04-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of Transaction')),
                ('type', models.CharField(choices=[('Debit', 'Debit'), ('Deposit', 'Deposit'), ('Credit', 'Credit'), ('Withdrawal', 'Withdrawal')], default='---', max_length=10, verbose_name='Type of Transaction')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('accountNum', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Account Number')),
                ('title', models.CharField(blank=True, choices=[('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.')], max_length=5)),
                ('firstName', models.CharField(max_length=15, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=15, verbose_name='Last Name')),
                ('startBal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Starting Balance')),
            ],
        ),
    ]
