# Generated by Django 3.2 on 2021-04-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit'), ('Debit', 'Debit'), ('Credit', 'Credit')], default='---', max_length=10, verbose_name='Type of Transaction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=5),
        ),
    ]
