# Generated by Django 3.2 on 2021-04-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0002_auto_20210408_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Withdrawal', 'Withdrawal'), ('Credit', 'Credit'), ('Deposit', 'Deposit')], default='---', max_length=10, verbose_name='Type of Transaction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.')], max_length=5),
        ),
    ]
