# Generated by Django 3.2 on 2021-04-09 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0003_auto_20210408_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accountNum',
        ),
        migrations.AddField(
            model_name='transaction',
            name='accountNum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkbook.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=5),
        ),
    ]
