# Generated by Django 3.2 on 2021-04-09 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0004_auto_20210408_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=5)),
                ('firstName', models.CharField(max_length=15, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=15, verbose_name='Last Name')),
                ('startBal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Starting Balance')),
            ],
            managers=[
                ('Accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('Transaction', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Credit', 'Credit')], default='---', max_length=10, verbose_name='Type of Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accountNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkbook.account'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
