# Generated by Django 3.2 on 2021-04-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0005_auto_20210409_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.')], max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit')], default='---', max_length=10, verbose_name='Type of Transaction'),
        ),
    ]
