# Generated by Django 3.2 on 2021-04-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0006_auto_20210409_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='title',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Deposit', 'Deposit'), ('Credit', 'Credit'), ('Withdrawal', 'Withdrawal')], default='---', max_length=10, verbose_name='Type of Transaction'),
        ),
    ]
