# Generated by Django 3.2 on 2021-04-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0007_auto_20210409_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Credit', 'Credit')], default='---', max_length=10, verbose_name='Type of Transaction'),
        ),
    ]
