# Generated by Django 3.2 on 2021-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0008_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Deposit', 'Deposit'), ('Debit', 'Debit'), ('Withdrawal', 'Withdrawal')], default='---', max_length=10, verbose_name='Type of Transaction'),
        ),
    ]
