# Generated by Django 3.2 on 2021-04-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0009_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.')], max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Deposit', 'Deposit'), ('Credit', 'Credit'), ('Withdrawal', 'Withdrawal')], default='---', max_length=10, verbose_name='Type of Transaction'),
        ),
    ]
