# Generated by Django 3.2 on 2021-04-09 21:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0010_auto_20210409_1247'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('Transactions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Withdrawal', 'Withdrawal'), ('Debit', 'Debit'), ('Deposit', 'Deposit')], default='---', max_length=10, verbose_name='Type of Transaction'),
        ),
    ]
