# Generated by Django 3.2 on 2021-04-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0011_auto_20210409_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='accountNum',
            new_name='account',
        ),
    ]
