# Generated by Django 3.2 on 2021-04-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0012_rename_accountnum_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Debit', 'Debit'), ('Withdrawal', 'Withdrawal'), ('Credit', 'Credit')], default='---', max_length=10, verbose_name='Type of Transaction'),
        ),
    ]
