# Generated by Django 3.2 on 2021-04-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0013_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=5),
        ),
    ]
